// openapi-fecth
// OpenAPIから生成した型定義pathsを使ってcreateClientでclientを出してくれる

import createClient from "openapi-fetch"
import type { paths } from "./v1" // generated by openapi-typescript

export const client = createClient<paths>({ baseUrl: "http://localhost:8000" })

// swr-openapi
// OpenAPIから生成した型定義pathsを使ってcreateQueryHookでqueryを出してくれる
import { createQueryHook } from "swr-openapi"
export const useQuery = createQueryHook(client, "my-api")
