// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { RootGetData, RootGetResponses, HelloGetHelloGetData, HelloGetHelloGetResponses, HelloGetHelloGetErrors, HelloPostHelloPostData, HelloPostHelloPostResponses, HelloPostHelloPostErrors } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Root
 */
export const rootGet = <ThrowOnError extends boolean = false>(options?: Options<RootGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<RootGetResponses, unknown, ThrowOnError>({
        url: '/',
        ...options
    });
};

/**
 * Hello Get
 * GET (パラメータあり)
 */
export const helloGetHelloGet = <ThrowOnError extends boolean = false>(options: Options<HelloGetHelloGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<HelloGetHelloGetResponses, HelloGetHelloGetErrors, ThrowOnError>({
        url: '/hello',
        ...options
    });
};

/**
 * Hello Post
 */
export const helloPostHelloPost = <ThrowOnError extends boolean = false>(options: Options<HelloPostHelloPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<HelloPostHelloPostResponses, HelloPostHelloPostErrors, ThrowOnError>({
        url: '/hello',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};