// This file is auto-generated by @hey-api/openapi-ts

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * PostParams
 */
export type PostParams = {
    /**
     * Text
     */
    text: string;
    /**
     * Number
     */
    number: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Response Root  Get
     * Successful Response
     */
    200: string;
};

export type RootGetResponse = RootGetResponses[keyof RootGetResponses];

export type HelloGetHelloGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Animal
         */
        animal: 'cat' | 'dog' | 'bird';
        /**
         * Number
         */
        number: number;
    };
    url: '/hello';
};

export type HelloGetHelloGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HelloGetHelloGetError = HelloGetHelloGetErrors[keyof HelloGetHelloGetErrors];

export type HelloGetHelloGetResponses = {
    /**
     * Response Hello Get Hello Get
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type HelloGetHelloGetResponse = HelloGetHelloGetResponses[keyof HelloGetHelloGetResponses];

export type HelloPostHelloPostData = {
    body: PostParams;
    path?: never;
    query?: never;
    url: '/hello';
};

export type HelloPostHelloPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HelloPostHelloPostError = HelloPostHelloPostErrors[keyof HelloPostHelloPostErrors];

export type HelloPostHelloPostResponses = {
    /**
     * Response Hello Post Hello Post
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type HelloPostHelloPostResponse = HelloPostHelloPostResponses[keyof HelloPostHelloPostResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};